SDLOPTS = -I/usr/local/include/SDL2 -I/opt/X11/include -D_THREAD_SAFE
CFLAGS = -O2 ${SDLOPTS}
CPPFLAGS = -std=c++11 -O2 ${SDLOPTS}
OBJECTS = app.o vgssdk_sdl2.o

all: $(OBJECTS)
	g++ -o app $(OBJECTS) -L/usr/local/lib -lsdl2

app.o: src/app.cpp src/vgssdk.h
	g++ $(CPPFLAGS) -c src/app.cpp

vgssdk_sdl2.o: src/vgssdk_sdl2.cpp src/vgssdk.h
	g++ $(CPPFLAGS) -c src/vgssdk_sdl2.cpp
